
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author almahedengren
 */
public class ChangeEmployeeInfoGUI extends javax.swing.JFrame {
    private String username;
    private InfDB idb;
    
    /**
     * Creates new form ChangeEmployeeInfoGUI
     */
    public ChangeEmployeeInfoGUI(String username) {
        initComponents();
        //Denna kod gör så att nya fönster öppnas i mitten av skärmen
        this.setLocationRelativeTo(null); 
        this.username = username;
        this.lblLoggedIn(lblLoggedIn, username);
        btnSaveName.setVisible(false);
        btnSavePassWord.setVisible(false);
        btnSaveUserName.setVisible(false);
        fillFields();
        
    }
     public void lblLoggedIn(JLabel textbox, String username) {
        textbox.setText("Du är inloggad som " + username + ".");
    } 
     
    public void fillFields (){
        txtUserName.setText(username);
        
        Employee anEmployee = new Employee(username);
        
        
        try {
            
        String namn = anEmployee.getName(username);    
        txtName.setText(namn);
        
        String passWord = anEmployee.getPassword(username);
        txtPassword.setText(passWord);
        
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "något gick fel");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoggedIn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnChangeUserName = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnChangeName = new javax.swing.JButton();
        btnSaveUserName = new javax.swing.JButton();
        btnSavePassWord = new javax.swing.JButton();
        btnSaveName = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoggedIn.setText("Inloggad som");
        getContentPane().add(lblLoggedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 256, -1, -1));

        btnBack.setText("Tillbaka");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 148, 200));

        jLabel2.setText("Användarnamn:");

        jLabel3.setText("Nytt lösenord:");

        jLabel4.setText("Namn:");

        txtUserName.setEditable(false);

        txtPassword.setEditable(false);

        txtName.setEditable(false);

        btnChangeUserName.setText("Ändra");
        btnChangeUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeUserNameActionPerformed(evt);
            }
        });

        btnChangePassword.setText("Ändra");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnChangeName.setText("Ändra");
        btnChangeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeNameActionPerformed(evt);
            }
        });

        btnSaveUserName.setText("Spara");
        btnSaveUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUserNameActionPerformed(evt);
            }
        });

        btnSavePassWord.setText("Spara");
        btnSavePassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePassWordActionPerformed(evt);
            }
        });

        btnSaveName.setText("Spara");
        btnSaveName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChangeUserName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChangePassword)
                            .addComponent(btnChangeName))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveUserName)
                    .addComponent(btnSavePassWord)
                    .addComponent(btnSaveName))
                .addGap(14, 14, 14))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtName, txtPassword, txtUserName});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangeUserName)
                    .addComponent(btnSaveUserName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePassword)
                    .addComponent(btnSavePassWord))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangeName)
                    .addComponent(btnSaveName))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new HomePageGUI(username).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnChangeUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeUserNameActionPerformed
        btnSaveUserName.setVisible(true);
        btnChangeUserName.setVisible(false);
                
        txtUserName.setEditable(true);
    }//GEN-LAST:event_btnChangeUserNameActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        btnSavePassWord.setVisible(true);
        btnChangePassword.setVisible(false);
                
        txtPassword.setEditable(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnChangeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeNameActionPerformed
        btnSaveName.setVisible(true);
        btnChangeName.setVisible(false);
                
        txtName.setEditable(true);
    }//GEN-LAST:event_btnChangeNameActionPerformed

    private void btnSavePassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePassWordActionPerformed
        if(Validation.checkEmpty(txtPassword)){
            try {
              Employee anEmployee = new Employee(username);
              
              anEmployee.setPassword(txtPassword.getText(), username);
              
              JOptionPane.showMessageDialog(null, "Lösenordet har ändrats.");
              
              btnSavePassWord.setVisible(false);
              btnChangePassword.setVisible(true);
              txtPassword.setEditable(false);
              
            } catch (InfException ex) {
                Logger.getLogger(ChangeEmployeeInfoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_btnSavePassWordActionPerformed

    private void btnSaveUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUserNameActionPerformed
    
        try {
            if(Validation.checkEmpty(txtUserName) && Validation.checkIfUserDoesNotExist(txtUserName)){
                try {
                    Employee anEmployee = new Employee(username);
                    
                    anEmployee.setUserName(txtUserName.getText(), username);
                    
                    JOptionPane.showMessageDialog(null, "Användarnamnet har ändrats.");
                    
                    btnSaveUserName.setVisible(false);
                    btnChangeUserName.setVisible(true);
                    txtUserName.setEditable(false);
                    
                } catch (InfException ex) {
                    Logger.getLogger(ChangeEmployeeInfoGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (InfException ex) {
            Logger.getLogger(ChangeEmployeeInfoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveUserNameActionPerformed

    private void btnSaveNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNameActionPerformed
       if(Validation.checkEmpty(txtName)){
            try {
              Employee anEmployee = new Employee(username);
              
              anEmployee.setName(txtName.getText(), username);
              
              JOptionPane.showMessageDialog(null, "Namnet har ändrats.");
              
              btnSaveName.setVisible(false);
              btnChangeName.setVisible(true);
              txtName.setEditable(false);
              
            } catch (InfException ex) {
                Logger.getLogger(ChangeEmployeeInfoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSaveNameActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangeEmployeeInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangeEmployeeInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangeEmployeeInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangeEmployeeInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChangeEmployeeInfoGUI(username).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChangeName;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnChangeUserName;
    private javax.swing.JButton btnSaveName;
    private javax.swing.JButton btnSavePassWord;
    private javax.swing.JButton btnSaveUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLoggedIn;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
