/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author almahedengren
 */

import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import oru.inf.InfDB;
import oru.inf.InfException;

public class ChangeHatInfoGUI extends javax.swing.JFrame {
    private String username;
   
    private InfDB idb;
    //private byte[] picture;
    private byte[] choosenImagee;

   
    /**
     * Creates new form ChangeHatInfo
     */
    public ChangeHatInfoGUI(String username) {
        initComponents();
              //Denna kod gör så att nya fönster öppnas i mitten av skärmen
        this.setLocationRelativeTo(null); 
        this.username = username;
        this.lblLoggedIn(lblLoggedIn, username);
        this.idb = HattmakarnaStudio.getDatabase();
        checkbBaseHat.setVisible(false);
        this.setTitle("Ändra hattinformation");
        try{
            fillCBHatName();
            }
        catch(Exception e){
            
            }
        
    }   
    
    private void fillCBHatName()
    {
        cbHatName.removeAllItems();
        lblSaved.setVisible(false);
        String hatQuery = "SELECT HATNAME FROM HAT ORDER BY HATNAME";

        ArrayList<String> allHats;

        try {
            allHats = idb.fetchColumn(hatQuery);
            cbHatName.addItem("Välj namn");
            for (String a : allHats) {
            cbHatName.addItem(a);
        }
        } 
        catch (InfException ex) {
            System.out.println("Det gick fel");
        }
}
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanelColor = new javax.swing.JPanel();
        jcbVit = new javax.swing.JCheckBox();
        jcbGrå = new javax.swing.JCheckBox();
        jcbBrun = new javax.swing.JCheckBox();
        jcbBeige = new javax.swing.JCheckBox();
        jcbRosa = new javax.swing.JCheckBox();
        jcbBlå = new javax.swing.JCheckBox();
        jcbGrön = new javax.swing.JCheckBox();
        jcbGul = new javax.swing.JCheckBox();
        jcbOrange = new javax.swing.JCheckBox();
        jcbRöd = new javax.swing.JCheckBox();
        jcbSvart = new javax.swing.JCheckBox();
        jcbLila = new javax.swing.JCheckBox();
        jPanelMaterial = new javax.swing.JPanel();
        jcbNylon = new javax.swing.JCheckBox();
        jcbSilke = new javax.swing.JCheckBox();
        jcbUll = new javax.swing.JCheckBox();
        jcbLäder = new javax.swing.JCheckBox();
        jcbBomull = new javax.swing.JCheckBox();
        jcbPolyester = new javax.swing.JCheckBox();
        jcbFleece = new javax.swing.JCheckBox();
        jcbLinne = new javax.swing.JCheckBox();
        jcbStrå = new javax.swing.JCheckBox();
        jcbKashmir = new javax.swing.JCheckBox();
        lblLoggedIn = new javax.swing.JLabel();
        jbUppdateraBild = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txFName = new javax.swing.JTextField();
        lblHat = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txANote = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        checkbBaseHat = new javax.swing.JCheckBox();
        btnBack = new javax.swing.JButton();
        lblSaved = new javax.swing.JLabel();
        txFPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbHatName = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txFHat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbBild = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 148, 200));

        jPanelColor.setBackground(new java.awt.Color(204, 204, 204));

        jcbVit.setText("Vit");

        jcbGrå.setText("Grå");

        jcbBrun.setText("Brun");

        jcbBeige.setText("Beige");

        jcbRosa.setText("Rosa");

        jcbBlå.setText("Blå");

        jcbGrön.setText("Grön");

        jcbGul.setText("Gul");

        jcbOrange.setText("Orange");

        jcbRöd.setText("Röd");

        jcbSvart.setText("Svart");

        jcbLila.setText("Lila");

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelColorLayout.createSequentialGroup()
                        .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbVit)
                            .addComponent(jcbGrå)
                            .addComponent(jcbBrun))
                        .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelColorLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbGrön)
                                    .addComponent(jcbBlå)))
                            .addGroup(jPanelColorLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jcbGul))))
                    .addGroup(jPanelColorLayout.createSequentialGroup()
                        .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbBeige)
                            .addComponent(jcbRosa))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbOrange)
                            .addGroup(jPanelColorLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbRöd)
                                    .addComponent(jcbLila)))))
                    .addComponent(jcbSvart))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbVit)
                    .addComponent(jcbBlå))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbGrå)
                    .addComponent(jcbGrön))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbBrun)
                    .addComponent(jcbGul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbBeige)
                    .addComponent(jcbOrange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSvart)
                    .addComponent(jcbLila))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbRosa)
                    .addComponent(jcbRöd))
                .addContainerGap())
        );

        jPanelMaterial.setBackground(new java.awt.Color(204, 204, 204));

        jcbNylon.setText("Nylon");

        jcbSilke.setText("Silke");
        jcbSilke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSilkeActionPerformed(evt);
            }
        });

        jcbUll.setText("Ull");

        jcbLäder.setText("Läder");

        jcbBomull.setText("Bomull");

        jcbPolyester.setText("Polyester");
        jcbPolyester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPolyesterActionPerformed(evt);
            }
        });

        jcbFleece.setText("Fleece");

        jcbLinne.setText("Linne");
        jcbLinne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLinneActionPerformed(evt);
            }
        });

        jcbStrå.setText("Strå");

        jcbKashmir.setText("Kashmir");

        javax.swing.GroupLayout jPanelMaterialLayout = new javax.swing.GroupLayout(jPanelMaterial);
        jPanelMaterial.setLayout(jPanelMaterialLayout);
        jPanelMaterialLayout.setHorizontalGroup(
            jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMaterialLayout.createSequentialGroup()
                        .addComponent(jcbNylon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbPolyester))
                    .addGroup(jPanelMaterialLayout.createSequentialGroup()
                        .addComponent(jcbLäder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbStrå))
                    .addGroup(jPanelMaterialLayout.createSequentialGroup()
                        .addComponent(jcbBomull)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbKashmir))
                    .addGroup(jPanelMaterialLayout.createSequentialGroup()
                        .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbSilke)
                            .addComponent(jcbUll))
                        .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMaterialLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jcbLinne))
                            .addGroup(jPanelMaterialLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jcbFleece)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanelMaterialLayout.setVerticalGroup(
            jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbNylon)
                    .addComponent(jcbPolyester))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSilke)
                    .addComponent(jcbFleece, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbUll)
                    .addComponent(jcbLinne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbLäder)
                    .addComponent(jcbStrå))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbBomull)
                    .addComponent(jcbKashmir))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        lblLoggedIn.setText("Inloggad som");

        jbUppdateraBild.setText("Uppdatera bild");
        jbUppdateraBild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUppdateraBildActionPerformed(evt);
            }
        });

        jLabel4.setText("Namn:");

        txFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFNameActionPerformed(evt);
            }
        });

        lblHat.setText("Hatttyp:");

        btnSearch.setText("Sök");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txANote.setColumns(20);
        txANote.setRows(5);
        jScrollPane1.setViewportView(txANote);

        btnSave.setText("Spara ändringar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        checkbBaseHat.setText("Gör specialhatt till basutbud");
        checkbBaseHat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbBaseHatActionPerformed(evt);
            }
        });

        btnBack.setText("Tillbaka");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblSaved.setBackground(new java.awt.Color(255, 255, 255));
        lblSaved.setFont(new java.awt.Font("Mukta Mahee", 2, 14)); // NOI18N
        lblSaved.setText("Uppdateringarna har sparats!");

        jLabel1.setText("Hatt:");

        cbHatName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj namn" }));
        cbHatName.setToolTipText("");
        cbHatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHatNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Anteckning:");

        jLabel2.setText("Pris:");

        jLabel6.setText("Färg: ");

        jLabel7.setText("Material:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkbBaseHat)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblSaved, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jbUppdateraBild)
                                    .addGap(33, 33, 33)
                                    .addComponent(btnSave))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLoggedIn)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbHatName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txFHat, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txFPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                                        .addComponent(txFName)))))
                                        .addGap(10, 10, 10))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHat, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(46, 46, 46)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jPanelMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbBild, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbHatName, txFPrice});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelMaterial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblLoggedIn)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(cbHatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txFPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txFHat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(2, 2, 2)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkbBaseHat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbUppdateraBild)
                            .addComponent(btnSave)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbBild, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaved)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbHatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHatNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbHatNameActionPerformed

    private void txFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFNameActionPerformed
   
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
            
            //Gör så att samtliga checkboxes .isSelected(false);
            Component[] colorComps = jPanelColor.getComponents();
            Component[] materialComps = jPanelMaterial.getComponents();
            for(Component comp : colorComps){
                if(comp instanceof JCheckBox)
               ((JCheckBox) comp).setSelected(false);
            }
            for(Component comp : materialComps){
                if(comp instanceof JCheckBox)
               ((JCheckBox) comp).setSelected(false);
            }
            
            markHatColorBoxes();
            markHatMaterialBoxes();
            
        txFName.setText("");
        txFPrice.setText("");
        txANote.setText("");
        txFHat.setText("");
        //jTextPane1.setText("");
        //jTextPane2.setText("");
        
      

        if(Validation.checkComboBox(cbHatName))
            {
            try{
            String getName = "SELECT HATNAME FROM HAT WHERE HATNAME = '" + cbHatName.getSelectedItem() + "'";
            String name = idb.fetchSingle(getName);
            txFName.setText(name);
            
            String getPrice = "SELECT PRICE FROM HAT WHERE HATNAME = '" + cbHatName.getSelectedItem() + "'";
            String price = idb.fetchSingle(getPrice);
            txFPrice.setText(price);
            
            String getNote = "SELECT NOTE FROM HAT WHERE HATNAME = '" + cbHatName.getSelectedItem() + "'";
            String note = idb.fetchSingle(getNote);
            txANote.setText(note);
            
            String getHat = "SELECT isSpecial FROM HAT WHERE HATNAME = '" + cbHatName.getSelectedItem() + "'";
            String hat = idb.fetchSingle(getHat);
            if(hat.equals("0")){
                txFHat.setText("Basutbud");
                 checkbBaseHat.setVisible(false);
            }
            else {
                txFHat.setText("Specialhatt");
                checkbBaseHat.setVisible(true);
            }
            
         
            
             String getqury = "SELECT PICTURE FROM HAT WHERE HATNAME = '" + cbHatName.getSelectedItem() + "'";
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HattDB", "hattdb", "hattkey");
                    PreparedStatement stmtt = conn.prepareStatement(getqury);
                    ResultSet rs = stmtt.executeQuery();
                    if (rs.next()) {
                        byte[] imagee = rs.getBytes("PICTURE");
                        ImageIcon imageI = new ImageIcon(imagee);
                        Image image1 = imageI.getImage().getScaledInstance(lbBild.getWidth(), lbBild.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon scaledIcon = new ImageIcon(image1);
                        lbBild.setIcon(scaledIcon);
            }
            
            }
            catch (InfException e)
            {
                
            } catch (SQLException ex) {
                Logger.getLogger(ChangeHatInfoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_btnSearchActionPerformed
}
        private void updateHatMaterials() {
        try{
            Component[] mComps = jPanelMaterial.getComponents();
            String hat = (String) cbHatName.getSelectedItem();
            String hatid = idb.fetchSingle("SELECT HatID FROM Hat WHERE HatName ='" + hat + "'");
            idb.delete("DELETE FROM IsOfMaterial WHERE HatID =" + hatid);
            
            for(Component comp : mComps){
                if(comp instanceof JCheckBox){
                    if(((JCheckBox) comp).isSelected()){
                    String point = (String) (((JCheckBox) comp).getText());
                    String mID = idb.fetchSingle("SELECT MaterialID FROM Material WHERE Material='" + point + "'");
                    idb.insert("INSERT INTO IsOfMaterial VALUES(" + mID + "," + hatid + ")");
                    }
                }
            }
        }catch(InfException e){
            System.out.println(e.getMessage());
        }
    }
    private void updateHatColors() {
        try{
        Component[] comps = jPanelColor.getComponents();
        String hat = (String) cbHatName.getSelectedItem();
        String hatid = idb.fetchSingle("SELECT HatID FROM Hat WHERE HatName='" + hat + "'");
        System.out.println("ID: " + hatid);
        idb.delete("DELETE FROM is_of_colour WHERE HatID =" + hatid);
        for(Component comp : comps){
            if(comp instanceof JCheckBox){
                if(((JCheckBox) comp).isSelected()){
                    String point = (String) (((JCheckBox) comp).getText());
                    System.out.println(point);
                    String cID = idb.fetchSingle("SELECT ColourID FROM HatColour WHERE Colour='" + point + "'");
                    System.out.println(point + " " + cID);
                    idb.insert("INSERT INTO is_of_colour VALUES(" + hatid + "," + cID + ")");
                }
            }
        }
        }catch(InfException e){
            System.out.println(e.getMessage() + " " +  e.getLocalizedMessage());
            e.getStackTrace();
        }
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(Validation.checkEmpty(txFName) && Validation.checkEmpty(txFPrice))
        {
            try{

            String newName = txFName.getText();
            
            String newPrice = txFPrice.getText();
           
            String newNote = txANote.getText();
            
            idb.fetchSingle("Update Hat Set HatName = '" + newName + "', Price = '" + newPrice + "', Note = '" + newNote + "' Where HatName = '" + cbHatName.getSelectedItem() + "'");
            
            //idb.delete("DELETE FROM IsOfMaterial JOIN Hat on HatID = HatID WHERE HatName ='" + cbHatName.getSelectedItem() + "'");

            if(checkbBaseHat.isSelected())
            {
                String newBase = "Update Hat set isSpecial = 0 where HatName = '" + cbHatName.getSelectedItem() + "'";
                idb.update(newBase); 
            

            lblSaved.setVisible(true);
            txFName.setText("");
            txFPrice.setText("");
            txANote.setText("");
            checkbBaseHat.setSelected(false);
            }
            else 
            {
            lblSaved.setVisible(true);
            txFName.setText("");
            txFPrice.setText("");
            txANote.setText(""); 
            checkbBaseHat.setSelected(false);
            }
            
            updateHatColors();
            updateHatMaterials();
            }
            catch (InfException e)
                    {
                        
                    } catch (Exception ex) {
                Logger.getLogger(ChangeHatInfoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * Fyller labeln Inloggad som och tar in det namn som man loggat in som som
     * parameter
     *
     * @param textbox
     * @param username
     */
    public static void lblLoggedIn(JLabel textbox, String username) {
        textbox.setText("Du är inloggad som " + username + ".");
    } 
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     new HatPageGUI(username).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jcbPolyesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPolyesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPolyesterActionPerformed

    private void jcbSilkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSilkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSilkeActionPerformed

    private void jbUppdateraBildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUppdateraBildActionPerformed
        // TODO add your handling code here:
     JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Bildfiler", "jpg", "png", "jpeg", "gif");
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);

        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            String fileName = selectedFile.getName();
            String extension = fileName.substring(fileName.lastIndexOf(".") + 1);

            if (!extension.equals("jpg") && !extension.equals("jpeg") && !extension.equals("png") && !extension.equals("gif")) {
                JOptionPane.showMessageDialog(null, "Felaktig filtyp. Välj en bildfil (jpg, jpeg, png eller gif).");
            } else {
                try {
                    
                    byte[] image = new byte[(int) selectedFile.length()];
                    FileInputStream fis = new FileInputStream(selectedFile);
                    fis.read(image);
                    
                    ImageIcon imageI = new ImageIcon(image);
                    Image image1 = imageI.getImage().getScaledInstance(lbBild.getWidth(), lbBild.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon scaledIcon = new ImageIcon(image1);
                    lbBild.setIcon(scaledIcon);

                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HattDB", "hattdb", "hattkey");
                    PreparedStatement stmt = conn.prepareStatement("Update HAT SET PICTURE = ? Where HatName = '" + cbHatName.getSelectedItem() + "'");
                    stmt.setBytes(1, image);
                    stmt.executeUpdate();
                    
                     } catch (Exception ex) {
                    Logger.getLogger(ChangeHatInfoGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jbUppdateraBildActionPerformed

    private void jcbLinneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLinneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbLinneActionPerformed

    private void checkbBaseHatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbBaseHatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkbBaseHatActionPerformed
    private void markHatMaterialBoxes(){
            try{
            ArrayList<String> hatMaterials = new ArrayList<>();
            String hatPick = cbHatName.getSelectedItem().toString();
            int hattid = Integer.parseInt(idb.fetchSingle("SELECT HatID FROM Hat WHERE HatName='" + hatPick + "'"));
            hatMaterials = idb.fetchColumn("SELECT MaterialID FROM IsOfMaterial WHERE HatID="+hattid);
            
            for(String mat : hatMaterials){
                System.out.println(mat);
                switch(mat){
                    case "1":
                        jcbBomull.setSelected(true);
                        break;
                    case "2":
                        jcbNylon.setSelected(true);
                        break;
                    case "3":
                        jcbPolyester.setSelected(true);
                        break;
                    case "4":
                        jcbFleece.setSelected(true);
                        break;
                    case "5":
                        jcbSilke.setSelected(true);
                        break;
                    case "6":
                        jcbUll.setSelected(true);
                        break;
                    case "7":
                        jcbKashmir.setSelected(true);
                    case "8":
                        jcbStrå.setSelected(true);
                        break;
                    case "9":
                        jcbLäder.setSelected(true);
                        break;
                    case "10":
                        jcbLinne.setSelected(true);
                        break;
                }
            }
            }catch(InfException e){
                System.out.println(e.getMessage());
                System.out.println(e.getLocalizedMessage());
            }
    }
    private void markHatColorBoxes() {
        
            try{
            ArrayList<String> hatColours = new ArrayList<>();
            String hatPick = cbHatName.getSelectedItem().toString();
            int hattid = Integer.parseInt(idb.fetchSingle("SELECT HatID FROM Hat WHERE HatName='" + hatPick + "'"));
            hatColours = idb.fetchColumn("SELECT ColourID FROM is_of_colour WHERE HatID ="+hattid);
            
            //Den här koden är katastrof men får duga så länge
            for(String color : hatColours){
                switch(color){
                    case "2":
                        jcbVit.setSelected(true);
                        break;
                    case "3" :
                        jcbGrå.setSelected(true);
                        break;
                    case "4":
                        jcbBrun.setSelected(true);
                        break;
                    case "5":
                        jcbBeige.setSelected(true);
                        break;
                    case "1" :
                        jcbSvart.setSelected(true);
                        break;
                    case "6":
                        jcbRosa.setSelected(true);
                        break;
                    case "8":
                        jcbBlå.setSelected(true);
                        break;
                    case "9":
                        jcbGrön.setSelected(true);
                        break;
                    case "10":
                        jcbGul.setSelected(true);
                        break;
                    case "11":
                        jcbOrange.setSelected(true);
                        break;
                    case "7":
                        jcbLila.setSelected(true);
                        break;
                    case "12":
                        jcbRöd.setSelected(true);
                        break;
                }
            }
                
            
            
        }catch(InfException e){
                System.out.println(e.getMessage());
                System.out.println(e.getLocalizedMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbHatName;
    private javax.swing.JCheckBox checkbBaseHat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JPanel jPanelMaterial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbUppdateraBild;
    private javax.swing.JCheckBox jcbBeige;
    private javax.swing.JCheckBox jcbBlå;
    private javax.swing.JCheckBox jcbBomull;
    private javax.swing.JCheckBox jcbBrun;
    private javax.swing.JCheckBox jcbFleece;
    private javax.swing.JCheckBox jcbGrå;
    private javax.swing.JCheckBox jcbGrön;
    private javax.swing.JCheckBox jcbGul;
    private javax.swing.JCheckBox jcbKashmir;
    private javax.swing.JCheckBox jcbLila;
    private javax.swing.JCheckBox jcbLinne;
    private javax.swing.JCheckBox jcbLäder;
    private javax.swing.JCheckBox jcbNylon;
    private javax.swing.JCheckBox jcbOrange;
    private javax.swing.JCheckBox jcbPolyester;
    private javax.swing.JCheckBox jcbRosa;
    private javax.swing.JCheckBox jcbRöd;
    private javax.swing.JCheckBox jcbSilke;
    private javax.swing.JCheckBox jcbStrå;
    private javax.swing.JCheckBox jcbSvart;
    private javax.swing.JCheckBox jcbUll;
    private javax.swing.JCheckBox jcbVit;
    private javax.swing.JLabel lbBild;
    private javax.swing.JLabel lblHat;
    private javax.swing.JLabel lblLoggedIn;
    private javax.swing.JLabel lblSaved;
    private javax.swing.JTextArea txANote;
    private javax.swing.JTextField txFHat;
    private javax.swing.JTextField txFName;
    private javax.swing.JTextField txFPrice;
    // End of variables declaration//GEN-END:variables

}
