import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JLabel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mattiasmesserer
 */
public class ChangeCustomerInfo extends javax.swing.JFrame {

    private String username;
    private InfDB idb;
    private ArrayList<String> cFornamn;
    private ArrayList<String> cEfternamn;
    private ArrayList<String> cCustomerID;
    private int id;
    /**
     * 
     * Creates new form ChangeCustomerInfo
     */
    public ChangeCustomerInfo(String username) {
        initComponents();
        this.username = username;
        this.lblUser(lblUser, username);
        this.setLocationRelativeTo(null);
        idb = HattmakarnaStudio.getDatabase();
        fillCustomerBox();
    }
    
    public void fillCustomerBox(){
        try{
        cFornamn = new ArrayList<>();
        cEfternamn = new ArrayList<>();
        cCustomerID = new ArrayList<>();
        cFornamn = idb.fetchColumn("SELECT FirstName FROM Customer");
        cEfternamn = idb.fetchColumn("SELECT LastName FROM Customer");
        cCustomerID = idb.fetchColumn("SELECT CustomerID FROM Customer");
        for(int i = 0; i < cFornamn.size(); i++){
            if(!cFornamn.get(i).equals("Anonym")){   
            jComboKunder.addItem(cFornamn.get(i) + " " + cEfternamn.get(i) + " - ID:" + cCustomerID.get(i));
            }
        }
        }catch(InfException e){
            System.out.println(e.getMessage());
        }
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblRubrik = new javax.swing.JLabel();
        jComboKunder = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jFieldFornamn = new javax.swing.JTextField();
        jFieldEfternamn = new javax.swing.JTextField();
        jFieldTelefon = new javax.swing.JTextField();
        jFieldEmail = new javax.swing.JTextField();
        jFieldHattStorlek = new javax.swing.JTextField();
        jFieldAdress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPostalNr = new javax.swing.JLabel();
        jFieldPostalNr = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        jFieldCity = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUser.setText("Du är inloggad som:");

        lblRubrik.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblRubrik.setText("Ändra kundinformation");

        jComboKunder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj kund..." }));
        jComboKunder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboKunderActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 148, 200));

        jFieldFornamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldFornamnActionPerformed(evt);
            }
        });

        jFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldEmailActionPerformed(evt);
            }
        });

        jLabel1.setText("Förnamn:");

        btnUpdate.setText("Uppdatera");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel2.setText("Efternamn:");

        jLabel3.setText("Telefon:");

        jLabel4.setText("Email:");

        jLabel5.setText("Hattstorlek:");

        jLabel6.setText("Adress:");

        lblPostalNr.setText("Postnummer:");

        lblCity.setText("Ort:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPostalNr)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFieldFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFieldEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFieldPostalNr, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFieldHattStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFieldAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(lblCity))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel6))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnUpdate)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFieldAdress, jFieldCity, jFieldEmail, jFieldHattStorlek});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFieldEfternamn, jFieldFornamn, jFieldPostalNr, jFieldTelefon});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFieldFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFieldEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFieldHattStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFieldAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostalNr)
                    .addComponent(lblCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFieldPostalNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnBack.setText("Tillbaka");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblUser)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRubrik)
                            .addComponent(jComboKunder, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser)
                .addGap(23, 23, 23)
                .addComponent(lblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboKunder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFieldFornamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldFornamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldFornamnActionPerformed

    private void jComboKunderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboKunderActionPerformed
        // TODO add your handling code here:
        String fullname = (String) jComboKunder.getSelectedItem();
        String[] idRay = fullname.split(":");
        System.out.println(idRay[1]);
        id = Integer.parseInt(idRay[1]);
        
        //String id = fullname.substring(fullname.lastIndexOf(": "));
        System.out.println(id);
        try{
        String firstName = idb.fetchSingle("SELECT FirstName FROM Customer WHERE CustomerID =" + id);
            System.out.println(firstName);
        String lastName = idb.fetchSingle("SELECT LastName FROM Customer WHERE CustomerID =" + id);
            System.out.println(lastName);
        String phone = idb.fetchSingle("SELECT Phone FROM Customer WHERE CustomerID =" + id);
            System.out.println(phone);
        String email = idb.fetchSingle("SELECT Email FROM Customer WHERE CustomerID =" + id);
            System.out.println(email);
        String hatSize = (String) idb.fetchSingle("SELECT HatSize FROM Customer WHERE CustomerID =" + id);
            System.out.println(hatSize);
        String adress = idb.fetchSingle("SELECT Address FROM Customer WHERE CustomerID=" + id);
            System.out.println(adress);
        String postalNr = idb.fetchSingle("SELECT PostalNr FROM Customer WHERE CustomerID=" + id);
        
        
        String city = idb.fetchSingle("SELECT City FROM Customer WHERE CustomerID=" + id);
        
        jFieldFornamn.setText(firstName);
        jFieldEfternamn.setText(lastName);
        jFieldTelefon.setText(phone);
        jFieldEmail.setText(email);
        jFieldHattStorlek.setText(hatSize);
        jFieldAdress.setText(adress);
        jFieldPostalNr.setText(postalNr);
        jFieldCity.setText(city);
        
        }catch(InfException e){
            System.out.println(e.getMessage() + " knas i comboaction ");
        }
        
    }//GEN-LAST:event_jComboKunderActionPerformed

    private void jFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldEmailActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
       String firstname = jFieldFornamn.getText();
       String lastName = jFieldEfternamn.getText();
       String phone = jFieldTelefon.getText();
       String mail = jFieldEmail.getText();
       String hatsize = jFieldHattStorlek.getText();
       String adress = jFieldAdress.getText();
       String postalNr = jFieldPostalNr.getText();
       String city = jFieldCity.getText();
        
        if(firstname.isEmpty() || lastName.isEmpty() || phone.isEmpty() || mail.isEmpty() || hatsize.isEmpty() || adress.isEmpty() || postalNr.isEmpty() || city.isEmpty()){
           JOptionPane.showMessageDialog(null, "Samtliga fält måste vara ifyllda.");
           
       }else{

        try{
        idb.update("UPDATE Customer SET FirstName = '" + firstname + 
                                      "', LastName = '" + lastName +
                                          "',Phone = '" + phone +
                                           "', Email = '" + mail + 
                                            "', HatSize = '" + hatsize +
                                               "', Address = '" + adress +
                                                   "', PostalNr = '" + postalNr +
                                                     "', City = '" + city +
                                                       "' WHERE CustomerID = " + id);
                    
        JOptionPane.showMessageDialog(null, "En kund har ändrats.");
        
        new ChangeCustomerInfo(username).setVisible(true);
        dispose();      
        
        }catch(InfException e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Error. Är samtliga fält korrekt ifyllda?");

        }
       }
    }//GEN-LAST:event_btnUpdateActionPerformed

     public static void lblUser(JLabel textbox, String username) {
        textbox.setText("Du är inloggad som " + username + ".");
    }
     
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new CustomerPageGUI(username).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> jComboKunder;
    private javax.swing.JTextField jFieldAdress;
    private javax.swing.JTextField jFieldCity;
    private javax.swing.JTextField jFieldEfternamn;
    private javax.swing.JTextField jFieldEmail;
    private javax.swing.JTextField jFieldFornamn;
    private javax.swing.JTextField jFieldHattStorlek;
    private javax.swing.JTextField jFieldPostalNr;
    private javax.swing.JTextField jFieldTelefon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblPostalNr;
    private javax.swing.JLabel lblRubrik;
    private static javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
